CREATE TABLE [dbo].[Error]
(
	[ErrorId] INT IDENTITY(1, 1) NOT NULL,
	[Type] VARCHAR(200) NOT NULL,
	[HResult] INT NOT NULL,
	[Message] VARCHAR(MAX) NOT NULL,
	[Source] VARCHAR(MAX) NULL,
	[StackTrace] VARCHAR(MAX) NULL,
	[TimeStamp] DATETIME NOT NULL CONSTRAINT [DF_Error_TimeStamp] DEFAULT GETDATE(),
	CONSTRAINT [PK_Error] PRIMARY KEY CLUSTERED ([ErrorId] ASC)
)